//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMonoClient.localhost {
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WcfMonoClient.localhost", ConfigurationName="IMyService")]
public interface IMyService {
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message GetDataRequest does not match the default value (WcfMonoClient.localhost)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetData", ReplyAction="http://tempuri.org/IMyService/GetDataResponse")]
    GetDataResponse GetData(GetDataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyService/GetData", ReplyAction="http://tempuri.org/IMyService/GetDataResponse")]
    System.IAsyncResult BeginGetData(GetDataRequest request, System.AsyncCallback callback, object asyncState);
    
    GetDataResponse EndGetData(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataRequest {
    
    public GetDataRequest() {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string GetDataResult;
    
    public GetDataResponse() {
    }
    
    public GetDataResponse(string GetDataResult) {
        this.GetDataResult = GetDataResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyServiceChannel : IMyService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyServiceClient : System.ServiceModel.ClientBase<IMyService>, IMyService {
    
    public MyServiceClient() {
    }
    
    public MyServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataResponse IMyService.GetData(GetDataRequest request) {
        return base.Channel.GetData(request);
    }
    
    public string GetData() {
        GetDataRequest inValue = new GetDataRequest();
        GetDataResponse retVal = ((IMyService)(this)).GetData(inValue);
        return retVal.GetDataResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMyService.BeginGetData(GetDataRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginGetData(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginGetData(System.AsyncCallback callback, object asyncState) {
        GetDataRequest inValue = new GetDataRequest();
        return ((IMyService)(this)).BeginGetData(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataResponse IMyService.EndGetData(System.IAsyncResult result) {
        return base.Channel.EndGetData(result);
    }
    
    public string EndGetData(System.IAsyncResult result) {
        GetDataResponse retVal = ((IMyService)(this)).EndGetData(result);
        return retVal.GetDataResult;
    }
}
